##########################################################################
#
# web访问端口号  约定: 8088
#
##########################################################################
server:
#  port: 8088
  tomcat:
    uri-enoding: UTF-8
  max-http-header-size: 80KB

##########################################################################
#
# 配置数据源信息
# !!! TODO 更改application name
#
##########################################################################
spring:
  application:
    name: cs-join-admin-service
  ### Feign - 当Bean名字一样的时候, 允许覆盖注册
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    #    password: zhoukuo
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长(毫秒),超过这个时长还没可用的连接则发生SQLException, 默认:30s
      minimum-idle: 5           # 最小连接数
      maximum-pool-size: 20     # 最大连接数
      auto-commit: true         # 自动提交
      idle-timeout: 600000      # 连接超时的最大时长(毫秒), 超时则被释放(retired), 默认:10分钟
      pool-name: DataSourceHikariCP # 连接池名字
      max-lifetime: 1800000     # 连接的生命时长(毫秒), 超时而且没被使用则被释放(retired), 默认:30分钟
      connection-test-query: SELECT 1 # 连接测试的SQL语句
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb
      # Spring Session 配置
#  session:
#    store-type: redis

##########################################################################
#
# mybatis 配置
# !!! TODO 更改路径
#
##########################################################################
mybatis:
  type-aliases-package: com.xiyoulinux.joinadmin.pojo           # 所有POJO类所在路径
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##########################################################################
#
# mybatis mapper 配置
#
##########################################################################
# 通用 Mapper 配置
mapper:
  mappers: com.xiyoulinux.my.mapper.MyMapper
  not-empty: false      # 在进行数据库操作的时候, 判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
