###
POST http://127.0.0.1:7002/cs-gateway/cs-auth/authority/login
Content-Type: application/json
#cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCIxMjNcIn0iLCJqdGkiOiIwZWJhNDRmYS1kZTQwLTRjNzktYWUwYi0wNmM2ZTkyZjY5NTQiLCJleHAiOjE2NDQ0NTg1MzR9.GGEq5k6OgBPzfpdUmIVxH3-4vtLAissLg2o3_o0ib42pJHz2dF7omz3GJOApUvBjFrlhRSzXJcEmaYaS98DayXToppj6U_r3DTsuM-ikpbs_16ehQB4ZPHa-jR9qLa_BTEAERHFqwi1pl38agleiiUWBcDwvqpeXP4eoNQSdpcoWOr9bciBO-pyK_OgNirsaNnYmOIghcxOIo_pArZeXq8i-fQCC664SMqxKsrqaANPWXhmV932f112kQjV4DeYqvFvg6ZUvMj56dOYUSa5NcuYy4XH_P6Foj2XJcWWohgz3rJhJTvhUucAStpHHC_IKsoSmY3WXlWv9Oj51nSVC1A

{
  "username": "123",
  "password": "123"
}
###cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIiqcInVzZXJuYW1lXCI6XCIxMjNcIn0iLCJqdGkiOiIyMzk1NGY2OS1kMjljLTRjZDMtYTE1Zi01ZTBjOGU0Y2JlZDEiLCJleHAiOjE2NDQyMzYxOTF9.I2it1RmRn_0nYI1lKwSJYuNaxPKGD7zKdG-Ma5RdpKyFYcFmHBxhRQI-YyQPba3oCKXB6l00z54h8dNRsnMSkruH_dWyxHppt_Lj37z0aIfzst5kVQJkxSTf0-I737haL6Nu1zTOjaavt7g_QqVl38NRUIVbSmGsFBscwxlJM-lsCCe8Lt3cOZTv83sa6RHw7HpnvNvuwAU6FfLLc-lCwjflhQay63NVPcrGmWjUHLExRaeUi-QqxmSB7Daqu9O9duL6kfoAlXacl2Gsk660n4gLjI7hrB-nAIjcrBI76rgS-iSZOCN32smkWDi-lpTpTtHoBOMaLEMtexCbWpy4zA
###

### Accept: application/json

