###
POST http://127.0.0.1:7002/cs-gateway/cs-auth/authority/login
Content-Type: application/json
#cs-user: eyJhbGciOiJSUzI1NiJ9.eyJhdXRoIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCIxMjNcIn0iLCJqdGkiOiIxNmM0M2RjMy04ODRkLTQ2Y2UtOWFkNS1kYTM1MGM1ZTZkM2YiLCJleHAiOjE2NDQzMTA0MDh9.SxZ4vd44LNpGJ29WKYADPO_T2d6io7zQ8znxgcQRoccDt4KaStywhmkYJilPZBtzTRIyqaLLMqyHpbfM0rCpXjm6F9HQ1rMk0yOq5qDYLiyXrEdgrO510t9hYTogjOsORMhcsPZaHF4pIPMhWpSMubxoRTM0MiOJXJGCRWxEvcpjZlSatsJxgfHwFGPP1jNCV4L-m3vJyXYLobcc9uL_OapMMJveKa-b83r9Az_rN09qThrgJNZRvzpICBFAVVcTmDyPicZM-b2dCGrl-DKIpQf69lLEsTIT4ym2phJdDs0JlsRYTDK8MnYBzSvZ-dcoGRVh70u3mQU1A4S8QiFcVg

{
  "username": "123",
  "password": "123"
}
###cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIiqcInVzZXJuYW1lXCI6XCIxMjNcIn0iLCJqdGkiOiIyMzk1NGY2OS1kMjljLTRjZDMtYTE1Zi01ZTBjOGU0Y2JlZDEiLCJleHAiOjE2NDQyMzYxOTF9.I2it1RmRn_0nYI1lKwSJYuNaxPKGD7zKdG-Ma5RdpKyFYcFmHBxhRQI-YyQPba3oCKXB6l00z54h8dNRsnMSkruH_dWyxHppt_Lj37z0aIfzst5kVQJkxSTf0-I737haL6Nu1zTOjaavt7g_QqVl38NRUIVbSmGsFBscwxlJM-lsCCe8Lt3cOZTv83sa6RHw7HpnvNvuwAU6FfLLc-lCwjflhQay63NVPcrGmWjUHLExRaeUi-QqxmSB7Daqu9O9duL6kfoAlXacl2Gsk660n4gLjI7hrB-nAIjcrBI76rgS-iSZOCN32smkWDi-lpTpTtHoBOMaLEMtexCbWpy4zA
###

### Accept: application/json

