###
POST http://127.0.0.1:8089/cs-activity-comment/activity-comment/add
Content-Type: application/json
Accept: application/json
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJlZWE0YzBjZi02NzI3LTRmNGItOTZlNC04NWYxZWI3Zjc2MjEiLCJleHAiOjE2NDIyNjI0MDB9.GcMfpzLdWUP1A-IvTspZVIcBF-twgD84TzojaWmAZE05gp--SzBoW2bOtAWzgtJe7NCvw7pkKFF4_kzbgFlygWrNw9lD0ywH3GcFhiWKQTHDkQ8a1q1XtPaoeiZMqHoqAIV8gBqNoNre_n4LZ-r7JnqAf356Bjk40AZEI_fJ_V2CEMMfSMps30-10YDXFVmdaXceGjsfD79E5KQXgsa5a9gyDbhhJlI15YVuZKac0b9ryY2N7_noU3q8c1bkUihdh7dZ8suJxRoFZFAZtfFp-7fycYZZTmGDeUNwSgrCKWkCKIlsbU2q69cAeyBSNwYRawzZS4mwct3fvwfnMabooA

{
  "userId": "1",
  "activityId": "21122509KK461BTC",
  "commentContent": "第1条问题的第3条评论",
  "commentCreateTime": "2021-12-25T19:00:00.000Z"
}

###
POST http://127.0.0.1:8089/cs-activity-comment/activity-comment/add
Content-Type: application/json
Accept: application/json
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJiNDNkZWRlMy04Y2EyLTQzMDctOTNhNC1jODM1ZmQ1ZjRjZjEiLCJleHAiOjE2NDEyMjU2MDB9.JM8SPTN_3sFQ0gC2G0xCXbSErWbWKzPka4CfiBZYpRDIYNddHy5Xk3az7-UjPnroGw9Pwcbbu3MkrqbPToxEgVZN3Z9fo-w4gTc0YeS-sUo9CiNkHchvcYqrsutLU5A5qYWJ87UQMxhBJZVlnE4niwWfQJuXRgbvycFmFyWmL-MbJH8nDq9Tc_k4q5JmYU22Vsa3iKWKsu9YTmQfghNAM6azgYUn-khYTegMnZtokvsdQB0wOY6KQur7c2da3KoWl9ddLptWVIDhVaIQWI_-iG-jof6JsDKveIgRMhZoj5wNALNZ7GQZrmKJYL3p7WatzFJ5vwTTtN3YgbHdnM84mQ

{
  "userId": "1",
  "activityId": "2112260S07GH41KP",
  "commentContent": "第8条问题的第2条评论",
  "commentCreateTime": "2021-12-25T19:00:00.000Z"
}

###
POST http://127.0.0.1:8089/cs-activity-comment/activity-comment/add
Content-Type: application/json
Accept: application/json
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJiNDNkZWRlMy04Y2EyLTQzMDctOTNhNC1jODM1ZmQ1ZjRjZjEiLCJleHAiOjE2NDEyMjU2MDB9.JM8SPTN_3sFQ0gC2G0xCXbSErWbWKzPka4CfiBZYpRDIYNddHy5Xk3az7-UjPnroGw9Pwcbbu3MkrqbPToxEgVZN3Z9fo-w4gTc0YeS-sUo9CiNkHchvcYqrsutLU5A5qYWJ87UQMxhBJZVlnE4niwWfQJuXRgbvycFmFyWmL-MbJH8nDq9Tc_k4q5JmYU22Vsa3iKWKsu9YTmQfghNAM6azgYUn-khYTegMnZtokvsdQB0wOY6KQur7c2da3KoWl9ddLptWVIDhVaIQWI_-iG-jof6JsDKveIgRMhZoj5wNALNZ7GQZrmKJYL3p7WatzFJ5vwTTtN3YgbHdnM84mQ

{
  "userId": "1",
  "activityId": "2112260S07GH41KP",
  "commentContent": "第8条任务的第3条评论",
  "commentCreateTime": "2021-12-25T19:00:00.000Z"
}

###
POST http://127.0.0.1:8089/cs-activity-comment/activity-comment/add
Content-Type: application/json
Accept: application/json
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJiNDNkZWRlMy04Y2EyLTQzMDctOTNhNC1jODM1ZmQ1ZjRjZjEiLCJleHAiOjE2NDEyMjU2MDB9.JM8SPTN_3sFQ0gC2G0xCXbSErWbWKzPka4CfiBZYpRDIYNddHy5Xk3az7-UjPnroGw9Pwcbbu3MkrqbPToxEgVZN3Z9fo-w4gTc0YeS-sUo9CiNkHchvcYqrsutLU5A5qYWJ87UQMxhBJZVlnE4niwWfQJuXRgbvycFmFyWmL-MbJH8nDq9Tc_k4q5JmYU22Vsa3iKWKsu9YTmQfghNAM6azgYUn-khYTegMnZtokvsdQB0wOY6KQur7c2da3KoWl9ddLptWVIDhVaIQWI_-iG-jof6JsDKveIgRMhZoj5wNALNZ7GQZrmKJYL3p7WatzFJ5vwTTtN3YgbHdnM84mQ

{
  "userId": "1",
  "activityId": "2112260S0GPBP0M8",
  "commentContent": "第9条任务的第1条评论",
  "commentCreateTime": "2021-12-25T19:00:00.000Z"
}

###
POST http://127.0.0.1:8089/cs-activity-comment/activity-comment/add
Content-Type: application/json
Accept: application/json
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJiNDNkZWRlMy04Y2EyLTQzMDctOTNhNC1jODM1ZmQ1ZjRjZjEiLCJleHAiOjE2NDEyMjU2MDB9.JM8SPTN_3sFQ0gC2G0xCXbSErWbWKzPka4CfiBZYpRDIYNddHy5Xk3az7-UjPnroGw9Pwcbbu3MkrqbPToxEgVZN3Z9fo-w4gTc0YeS-sUo9CiNkHchvcYqrsutLU5A5qYWJ87UQMxhBJZVlnE4niwWfQJuXRgbvycFmFyWmL-MbJH8nDq9Tc_k4q5JmYU22Vsa3iKWKsu9YTmQfghNAM6azgYUn-khYTegMnZtokvsdQB0wOY6KQur7c2da3KoWl9ddLptWVIDhVaIQWI_-iG-jof6JsDKveIgRMhZoj5wNALNZ7GQZrmKJYL3p7WatzFJ5vwTTtN3YgbHdnM84mQ

{
  "userId": "1",
  "activityId": "2112260S0GPBP0M8",
  "commentContent": "第9条任务的第2条评论",
  "commentCreateTime": "2021-12-25T19:00:00.000Z"
}

###
PUT http://127.0.0.1:8089/cs-activity-comment/activity-comment/dislike/220103BZZ4G42FFW/1
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJiNDNkZWRlMy04Y2EyLTQzMDctOTNhNC1jODM1ZmQ1ZjRjZjEiLCJleHAiOjE2NDEyMjU2MDB9.JM8SPTN_3sFQ0gC2G0xCXbSErWbWKzPka4CfiBZYpRDIYNddHy5Xk3az7-UjPnroGw9Pwcbbu3MkrqbPToxEgVZN3Z9fo-w4gTc0YeS-sUo9CiNkHchvcYqrsutLU5A5qYWJ87UQMxhBJZVlnE4niwWfQJuXRgbvycFmFyWmL-MbJH8nDq9Tc_k4q5JmYU22Vsa3iKWKsu9YTmQfghNAM6azgYUn-khYTegMnZtokvsdQB0wOY6KQur7c2da3KoWl9ddLptWVIDhVaIQWI_-iG-jof6JsDKveIgRMhZoj5wNALNZ7GQZrmKJYL3p7WatzFJ5vwTTtN3YgbHdnM84mQ

###
PUT http://127.0.0.1:8089/cs-activity-comment/activity-comment/like
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcIXnVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJlZWE0YzBjZi02NzI3LTRmNGItOTZlNC04NWYxZWI3Zjc2MjEiLCJleHAiOjE2NDIyNjI0MDB9.GcMfpzLdWUP1A-IvTspZVIcBF-twgD84TzojaWmAZE05gp--SzBoW2bOtAWzgtJe7NCvw7pkKFF4_kzbgFlygWrNw9lD0ywH3GcFhiWKQTHDkQ8a1q1XtPaoeiZMqHoqAIV8gBqNoNre_n4LZ-r7JnqAf356Bjk40AZEI_fJ_V2CEMMfSMps30-10YDXFVmdaXceGjsfD79E5KQXgsa5a9gyDbhhJlI15YVuZKac0b9ryY2N7_noU3q8c1bkUihdh7dZ8suJxRoFZFAZtfFp-7fycYZZTmGDeUNwSgrCKWkCKIlsbU2q69cAeyBSNwYRawzZS4mwct3fvwfnMabooA
Content-Type: application/json

{
  "csCommentId": "211225DBF9M8FPPH",
  "csUserId": "1",
  "activityId": "21122509RFD57KWH"
}

###
GET http://127.0.0.1:8089/cs-activity-comment/activity-comment/get/21122509RFD57KWH/1
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJlZWE0YzBjZi02NzI3LTRmNGItOTZlNC04NWYxZWI3Zjc2MjEiLCJleHAiOjE2NDIyNjI0MDB9.GcMfpzLdWUP1A-IvTspZVIcBF-twgD84TzojaWmAZE05gp--SzBoW2bOtAWzgtJe7NCvw7pkKFF4_kzbgFlygWrNw9lD0ywH3GcFhiWKQTHDkQ8a1q1XtPaoeiZMqHoqAIV8gBqNoNre_n4LZ-r7JnqAf356Bjk40AZEI_fJ_V2CEMMfSMps30-10YDXFVmdaXceGjsfD79E5KQXgsa5a9gyDbhhJlI15YVuZKac0b9ryY2N7_noU3q8c1bkUihdh7dZ8suJxRoFZFAZtfFp-7fycYZZTmGDeUNwSgrCKWkCKIlsbU2q69cAeyBSNwYRawzZS4mwct3fvwfnMabooA
Content-Type: application/json

{
  "page": 1,
  "size": 10
}

###
GET http://127.0.0.1:8089/cs-activity-comment/activity-comment/orderbyLikes/21122509RFD57KWH/1
cs-user: eyJhbGciOiJSUzI1NiJ9.eyJjcy11c2VyIjoie1wiaWRcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJxa21cIn0iLCJqdGkiOiJlZWE0YzBjZi02NzI3LTRmNGItOTZlNC04NWYxZWI3Zjc2MjEiLCJleHAiOjE2NDIyNjI0MDB9.GcMfpzLdWUP1A-IvTspZVIcBF-twgD84TzojaWmAZE05gp--SzBoW2bOtAWzgtJe7NCvw7pkKFF4_kzbgFlygWrNw9lD0ywH3GcFhiWKQTHDkQ8a1q1XtPaoeiZMqHoqAIV8gBqNoNre_n4LZ-r7JnqAf356Bjk40AZEI_fJ_V2CEMMfSMps30-10YDXFVmdaXceGjsfD79E5KQXgsa5a9gyDbhhJlI15YVuZKac0b9ryY2N7_noU3q8c1bkUihdh7dZ8suJxRoFZFAZtfFp-7fycYZZTmGDeUNwSgrCKWkCKIlsbU2q69cAeyBSNwYRawzZS4mwct3fvwfnMabooA
Content-Type: application/json

{
  "page": 1,
  "size": 10
}
